### ISSUE TITLE
The Minskins review 20/08/2020

### ISSUE THREAD

**Issue by WinterCore** [carlosveigadev/slack-10-min-office-workout#1]
Great project. Rubocop would approve.

Small notes to remember:
- Don't forget to update your readme with your project's details.
- Don't forget to share the API keys or upload the project to Heroku when submitting it for code review.

And here's bender dancing. Use it as an inspiration.

![](https://64.media.tumblr.com/tumblr_ma0id4kYlv1rv5x9bo1_400.gifv)

**Comment by carlosveigadev** [comment]
Thanks guys for the suggestion =D
